name: 'Node 12 Template Action'
description: 'Get started with Node actions'
author: 'GitHub'
inputs: 
  path-to-signatures:
    description: 'Give a path for storing CLAs in a json file '
    default: './signatures/cla.json'
  branch:
    description: 'select a branch where all the CLAs are stored'
    default: 'master'
  blockchain-storage-flag:
    description: 'Optional functionality to store all the blockchain signatures in the ethirium blockchain as a smart contract'
    default: false
runs:
  using: 'node12'
  main: 'lib/main.js'
